### PR TITLE
Create new Mobility section and redirect existing docs into it

### LINKED ISSUE #180: Create a mobility section
Pulls together matrix, optimized, turn-by-turn into one section and add appropriate redirects. Add home section for mobility to match the product page.

Elevation is under data, so no changes there.

### PR DESCRIPTION
**Pull request by migurski**
Closes #180.

### CODE REVIEW

**Comment by rmglennon** [comment]
Confirmed, the "Edit this page" links in our renamed files are broken. :(

Sample 404s
https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda-new-mobility/documentation/mobility/optimized/api-reference/
-->
https://github.com/valhalla/valhalla-docs/tree/master/optimized/api-reference.md
--> correct location (optimized_route)
https://github.com/valhalla/valhalla-docs/blob/master/optimized_route/api-reference.md

https://precog.mapzen.com/mapzen/mapzen-docs-generator/rhonda-new-mobility/documentation/mobility/turn-by-turn/api-reference/
-->
https://github.com/valhalla/valhalla-docs/tree/master/turn-by-turn/api-reference.md
--> correct location (no turn-by-turn)
https://github.com/valhalla/valhalla-docs/tree/master/api-reference.md

**Comment by migurski** [comment]
Cheap and easy fix: link to the top of the documentation section on Github and let people figure out what to edit.

Harder fix: track the files we are renaming and ensure the links go to the right places.

**Comment by migurski** [comment]
I think I’ve fixed this. The only new twist is that `mz:renames` now must use filenames instead of directory names, so that the renaming can be found in the template.

**Comment by rmglennon** [comment]
Hooray, looks good so far...will do some testing.

**Comment by rmglennon** [comment]
New thing...@kkowalsky found that images are broken links. The only topic with images is documentation/mobility/turn-by-turn/add-routing-to-a-map/, but I'd assume it'd be a problem with any of them.

Broken link example:
documentation/mobility/turn-by-turn/images/browser-controls.png

I'm not yet sure where the images actually live...still looking.

**Comment by rmglennon** [comment]
Remaining items are content-related and will be done in the valhalla-docs repository.

**Pull request merged**
