### PR TITLE
WIP: add terrain tiles docs

### PR DESCRIPTION
**Pull request by nvkelso**
**Coordinate with blog post going up Tuesday Oct. 11th, 2016**

WARNING: Don't merge this until service goes live!

- [x] Uncomment out the Terrain Tiles bit on the docs index.html page.
  - https://github.com/mapzen/website/pull/1204 has the product page change
- [x] Even more `terrain-tiles-xxx` > `mapzen-xxx` edits.
- [x] Smaller preview image file size.
- [x] Any other last minute edits
- [x] Tag joerd v1.0.0 release.
- [x] Update Makefile to point at release (not SHA)
- [x] Launch v1.0.0 terrain tile service (Fastly config)

_Contains a both updates to the (hidden) Mapzen Terrain Tiles service and makes that hidden content visible off the main docs homepage._

### CODE REVIEW

**Comment by migurski** [comment]
Is this PR still correct? It replaces https://github.com/tilezen/joerd/commit/20b4512754490477b0594e3017b278361ad5af80 (12 days old) with the older https://github.com/tilezen/joerd/commit/a3cf077338e298c5f6d61d3ba3e017b130258fe7 (21 days old).

**Comment by nvkelso** [comment]
@migurski I've updated it with a newer SHA, thanks for the catch!

**Comment by migurski** [comment]
👍 

Also, can we get the image on the front page converted to a JPG? At 3.5MB it’s about 10x too large for a picture on a web page.

**Comment by nvkelso** [comment]
@migurski yep :) looks like the walkabout example image was also over 1 MB, fixing that, too.

**Comment by nvkelso** [comment]
@rmglennon @kkowalsky Can you have a final look over this, please?

- [documentation homepage](https://precog.mapzen.com/mapzen/mapzen-docs-generator/nvkelso/add-elevation-tile-docs/documentation/) - Adds Terrain tiles, modifies Vector tiles description.
- [rate-limits overview](https://precog.mapzen.com/mapzen/mapzen-docs-generator/nvkelso/add-elevation-tile-docs/documentation/overview/#rate-limits) - Adds Terrain tiles.
- [terrain tiles docs](https://precog.mapzen.com/mapzen/mapzen-docs-generator/nvkelso/add-elevation-tile-docs/documentation/terrain-tiles/) - What we released last month, but with smaller image sizes and fixed Mapzen API key usage (there were some strangler `terrain-tiles-xxxxxx` references).

**Comment by nvkelso** [comment]
_The blog post ([precog](https://precog.mapzen.com/mapzen/website/nvkelso/official-terrain-tiles-v1/blog/terrain-tile-service) preview) announcing the service has it's own PR over [there](https://github.com/mapzen/website/pull/1204)._

**Comment by nvkelso** [comment]
Also of note, there is no special Terrain Tiles product page. Instead it jumps directly to the documentation (like Mapzen.js). Maybe someday we'll have a special product page, but that day in the medium to distant future.

**Comment by kkowalsky** [comment]
@nvkelso looks good, but can you revise the blog email to be tiles@mapzen.com? It'll be easier to know what people are referring to if commenting on the blog post. 

Added a [PR](https://github.com/tilezen/joerd/pull/107) in joerd with some minor edits

@rmglennon @migurski what do you think of the description for vector tiles? [precog](https://precog.mapzen.com/mapzen/mapzen-docs-generator/nvkelso/add-elevation-tile-docs/documentation/)

**Comment by migurski** [comment]
“Display the world with the latest open data using vector tiles” feels a bit more promotional than strictly right for a docs page, but I could live with it.

**Comment by rmglennon** [comment]
Yeah, same thoughts on the tag line. It's fine for now. I'd like to do another pass through the whole page (for example, some say "global" or "open", which could indicate those that don't include those words are not that).

**Comment by rmglennon** [comment]
Now may not be the time, as in, we could do this in a whole pass when reviewing the content or as part of some other product team work this quarter to add consistency...

Doc banner is "Vector Tile Service"
Doc tag line is "Add open geospatial data to your applications with the vector tile map service."
Doc home page title "Mapzen Vector Tiles" (NOTE: There should not be a title on the index page anyway.)
Doc home page first sentence is "The Mapzen vector tile service provides worldwide... "
Doc landing page section is "Vector tiles", and tag line is "Display the world with the latest open data using vector tiles."

The terrain tiles pages are following this trend, too, with calling it "Terrain Tile Service," "raster tile map service", and "Mapzen terrain tiles" at the top of the first doc page.

**Comment by nvkelso** [comment]
Everything looks like a party on Precog, merging.

**Pull request merged**
