### PR TITLE
add global

### PR DESCRIPTION
**Pull request by meetar**

### CODE REVIEW

**Comment by meetar** [comment]
Good morning @louh @migurski! Any idea what this Circle error means?

> AssertionError: 4 != 3 : There should be three breadcrumbs at top at /tangram/Scene-file/index.html

**Comment by migurski** [comment]
It’s a test that I wrote to ensure that the output of the docs “looks right”. It’s complaining that there’s an extra breadcrumb in the navigation up here, which does indeed look really odd to me as well:

screen shot 2016-04-25 at 8 25 11 am

**Comment by meetar** [comment]
Ahh, breadcrumb = navigation level? That does look a bit cramped. Okay, will revise. Thanks!

**Comment by rmglennon** [comment]
Wow, that is some funky table of contents formatting!

**Comment by migurski** [comment]
Replaced by #135.

**Pull request closed without merging**
