### PR TITLE
New Index page 

### PR DESCRIPTION
**Pull request by hanbyul-here**
- New index page for docs page

### CODE REVIEW

**Comment by kkowalsky** [comment]
before we do this, I have some text to edit

**Comment by kkowalsky** [comment]
just edited, @rmglennon do you want to double check?

**Comment by rmglennon** [comment]
The Turn-by-Turn link will change to Mobility as soon as I get the new mobility doc section on the website.

**Comment by kkowalsky** [comment]
the text is 💯 until we change mobility, but @hanbyul-here can we add back the email box? If we can do that but override/remove the 'get involved' section I think we'll be done

**Comment by rmglennon** [comment]
This page is great. Thank you @hanbyul-here @kkowalsky.

**Comment by hanbyul-here** [comment]
This pr should go with https://github.com/mapzen/styleguide/pull/289 and https://github.com/mapzen/website/pull/1083

**Pull request merged**
