### PR TITLE
Change to scheduled run

### LINKED ISSUE #106: Switch from event-based CircleCI deployment to frequent scheduled task
Docs are driven by external repositories, so we need this one to operate on a schedule instead of based on events.

### PR DESCRIPTION
**Pull request by migurski**
Switched to a layout compatible with [Heroku scheduler](https://devcenter.heroku.com/articles/scheduler), which we can run continuously.

- Moved `deploy` task to `Procfile` for scheduler.
- Moved dangling package installations to `requirements.txt` where Heroku can see them.
- Introduced dependency on `AWS_DESTINATION` environment variable.

To do:

* [x] Check with @baldur that this is kosher.
* [x] Introduce build consistency check [per Rhonda’s list](https://github.com/mapzen/mapzen-docs-generator/issues/95).
* [x] Complete set up of [`mapzen-docs-generator` app](https://dashboard.heroku.com/apps/mapzen-docs-generator).
* [x] Add note in README pointing to Heroku scheduled task.

Closes #106, #95.

### CODE REVIEW

**Comment by migurski** [comment]
Checked with Baldur, he says this is okay as an hourly cron task for now, but would like to see it additionally supported with a webhook from the linked repositories in the near future.

**Comment by rmglennon** [comment]
See also original issue: #54

**Comment by migurski** [comment]
I added a checklist for structural elements that can be determined without a CSS rendering browser.

**Comment by migurski** [comment]
Heroku app is now pushing to `dev.mapzen.com` hourly.

**Pull request merged**
