### PR TITLE
nvkelso/update vector tile docs

### PR DESCRIPTION
**Pull request by nvkelso**
* source vector-tile docs from new location
* expand doc coverage

I've verified it locally, but I'm not a pro at this system so please verify it again!

### CODE REVIEW

**Comment by rmglennon** [comment]
@nvkelso @louh @migurski - So this deprecates the vector-tiles-service-docs repo and moves all the docs under vector-datasource?

**Comment by nvkelso** [comment]
Yep, I've updated the old location to point people to mapzen.com for live docs, and the vector-datasource repo for src docs.

**Comment by nvkelso** [comment]
@louh I see this merged (thanks!), but I don't see the new content live on mapzen.com?

**Comment by rmglennon** [comment]
It's only on dev internal site for now. We'll test there and send to
production once verified.

**Comment by louh** [comment]
Never deploy on Friday afternoon!

Dev also failed to publish, it seems. Here are logs from Circle:

```
Building Vector Tiles documentation...
Loading: ./config/default.yml
Loading: ./config/vector-tiles.yml
Dumping: ./mkdocs.yml
INFO    -  Cleaning site directory 
INFO    -  Building documentation to directory: /home/ubuntu/mapzen-docs-generator/dist/vector-tiles 
ERROR   -  file not found: /home/ubuntu/mapzen-docs-generator/src/vector-tiles/docs/index.md 
ERROR   -  Error building page docs/index.md 
Traceback (most recent call last):
  File "/home/ubuntu/virtualenvs/venv-3.4.3/bin/mkdocs", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/mkdocs/cli.py", line 134, in build_command
    ), clean_site_dir=clean)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/mkdocs/build.py", line 299, in build
    build_pages(config)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/mkdocs/build.py", line 259, in build_pages
    dump_json)
  File "/home/ubuntu/virtualenvs/venv-3.4.3/lib/python3.4/site-packages/mkdocs/build.py", line 171, in _build_page
    input_content = io.open(input_path, 'r', encoding='utf-8').read()
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/mapzen-docs-generator/src/vector-tiles/docs/index.md'
make: *** [vector-tiles] Error 1
```

Let's review on Tuesday.

**Comment by migurski** [comment]
Derp, yes. I’d love to wrap up Tuesday with a map of our docs similar to the ones @heffergm has been making for his excellent blog posts:

mapzen monitoring metrics

**Comment by rmglennon** [comment]
@nvkelso - this is fixed now and on production. The code changes are in commits here: https://github.com/mapzen/mapzen-docs-generator/pull/105

**Pull request merged**
